### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by InLearningPhase** [dbc2201/gla-bcsc0001-2018#21]
#include <stdio.h>
int main()
{
    int a = 1;
    if (a);
    {
        printf("hello");
    }
    else
    {
        printf("world");
    }
    return 0;
}

#include <stdio.h>
int main()
{
    int a = 97;
    if (a == 'a');
    else
        printf("hello");
    printf("world");
return 0;
}

What is the difference between these two codes??
In first one, code is giving error "else without previous if"
but not giving in second code....why??
Both are looking pretty similar.

**Comment by dbc2201** [comment]
You can see #9 for the explanation.

**Comment by InLearningPhase** [comment]
Thank you sir...i got it!!
