### ISSUE TITLE
Unable to get expected output.

### ISSUE THREAD

**Issue by 10shubhamsingh** [dbc2201/gla-bcsc0001-2018#26]
void sort (int *,int);
#include<stdio.h>
void main ()
{
	int a[10]={10,20,15,25,30,40,35,50,55,45},i;
	sort(a,10);
	for(i=0;i<10;i++)
	{
		printf("%d",a[i]);
	}
}
sort (int *x,int y)
{
	int i,j,temp;
	for(i=0;i<y;i++)
	{
		for(j=0;j<i-y-1;j++)
		{
			if(x[i]>x[i+1])
			{
				temp=x[i];
				x[i]=x[i+1];
				x[i+1]=temp;
			}
		}
	}
}

**Comment by dbc2201** [comment]
@10shubhamsingh 
___
```c
#include<stdio.h>

void sort (int *, int);

int main(void)
{
    int a[10] = {10, 20, 15, 25, 30, 40, 35, 50, 55, 45}, i;
    sort(a, 10);
    for( i = 0 ; i < 10 ; i++ )
    {
        printf("%d ", a[i]);
    }
}

void sort (int *x, int y)
{
    int i, j, temp;
    for( i = 0 ; i < y ; i++ )
    {
        for( j = 0 ; j < y ; j++ )
        {
            if( x[i] > x[i + 1] )
            {
                temp = x[i];
                x[i] = x[i + 1];
                x[i + 1] = temp;
            }
        }
    }
}
```
I hope this solves your problem
