### ISSUE TITLE
link my my worksheet 5 is here...

### ISSUE THREAD

**Issue by sarvendrasingh** [dbc2201/gla-bcsc0001-2018#30]
[https://github.com/sarvendrasingh/C_Programming_Worksheet_5](url)

**Comment by sarvendrasingh** [comment]
can somebody  help me explaining the function of **break** used  in question no. 4 please....
[https://github.com/sarvendrasingh/C_Programming_Worksheet_5/blob/master/sources/4.c](url)

**Comment by dbc2201** [comment]
The links are not working.
