### ISSUE TITLE
worksheet 2 ,doubt in ques 11, 12

### ISSUE THREAD

**Issue by kshitizguptaa** [dbc2201/gla-bcsc0001-2018#31]
what is mean of "~" this sign & i don't understand the output of ques 11 and 12
Q11.
int main()
{
    int c = 10, d = 20, e = 30;
    d = !e;
	e = ~d;
	printf("%d %d", d, e);
}
Q12.
int main()
{
    int c = 10, d = 20, e = 30;
    d = !d;
	e = ~e;
	printf("%d %d", d, e);
}

**Comment by dbc2201** [comment]
@kshitizguptaa The `~` operator is the bitwise operator. You can visit [this link](https://www.programiz.com/c-programming/bitwise-operators) for a handy guide in *bitwise operators in C*. Whereas the `!` is the logical `NOT` operator. It would just change the values of every bit of the number to the opposite.
!1 = 0 
!0 = 1
e. g
!(1010) = 0101
