### ISSUE TITLE
doubt in worksheet_5 #Que._no. : 4,15,21 

### ISSUE THREAD

**Issue by RakeshY008** [dbc2201/gla-bcsc0001-2018#35]
sir please explain above mentioned ques.

**Comment by divaibhav** [comment]
in question no 5
```c
#include <stdio.h>
int main()
{
    int i = 5;
 	do
 	while (i--);
 	printf("%d", i); 
    return 0;
}
````
as per do while syntax , there will be at least one statement in between do and while. That's why it will generate parsing error before the next statement after while. In this particular question error before printf().

**Comment by divaibhav** [comment]
in question no 21
```C
#include <stdio.h>
int main()
{
	int i = 5;
	goto one;
	break;
	one:
	printf("%d",i);
	--i;
    return 0;
}
```
break statement can only used within loop, so it will generate error.

**Comment by RakeshY008** [comment]
> in Question no 4
> 
> ```c
> #include <stdio.h>
> int main()
> {
>     int i = 2;
> 	one:
> 	two:
> 	for ( ; ; i++ )
>     {
> 		if ( i % 2 == 0 ) 
>         {
> 			goto one;
> 			printf("%d", i);
> 		}
> 		else
>         {
> 			break;
>             goto two;
> 			printf("%d", i);
> 		}
> 	}
> 	return 0;    
> }
> ```
> 
> goto one is never letting the for loop to complete and value of "i" will always be 2, that why it is giving no output, but goto one leads to infinite loop.
> 
> the correct answer of the question is infinite loop due to goto statement.


>#divaibhav thank you !!!!

**Comment by RakeshY008** [comment]
> in question no 5
> 
> ```c
> #include <stdio.h>
> int main()
> {
>     int i = 5;
>  	do
>  	while (i--);
>  	printf("%d", i); 
>     return 0;
> }
> ```
> 
> as per do while syntax , there will be at least one statement in between do and while. That's why it will generate parsing error before the next statement after while. In this particular question error before printf().

>>>   okyee got it 💯 👍      `#divaibhav

**Comment by dbc2201** [comment]
@divaibhav Sir, thank you for the explanation.
