### ISSUE TITLE
doubt @RakeshY008

### ISSUE THREAD

**Issue by RakeshY008** [dbc2201/gla-bcsc0001-2018#36]
problem of Worksheet 6 

Que.1 :  not getting logic of que,1, what we have to do in it ......... " Write a program in C to display the ASCII code of a character and vice versa. "

#que.4 :

An electricity board charges according to following rates:
 For the first 100 units - 40 P per unit,
For the next 200 units - 50 P per unit,
Beyond 300 units - 60 P per unit.
All users are charged a meter charge too, which is Rs 50/-
Write a program in C to read the names of users and number of units consumed, and print out the charges with names.

**_MY SOURCE_CODE_**

#include<stdio.h>
#include<string.h>
int main()
{
        char name[50];
        float rupia_btauu;
        int kitna_unit_jaoge_Janab, unit_krcha, meret_charge = 50 ;

        printf("Enter Your Name:    ");
        scanf("%s\n", &name);

        printf("Distance (in meter):    ");
        scanf(" %d\n ", &kitna_unit_jaoge_Janab);
        float x = 0.0 , y = 0.0 , z = 0.0;

        if (kitna_unit_jaoge_Janab > 0 )
        {

            if( kitna_unit_jaoge_Janab > 0 && kitna_unit_jaoge_Janab <= 100 )
                {
                    x = 0.4*kitna_unit_jaoge_Janab;
                }

            if( kitna_unit_jaoge_Janab > 100 && kitna_unit_jaoge_Janab <= 300 )
                {
                      y = 0.5*kitna_unit_jaoge_Janab;
                }

            if ( kitna_unit_jaoge_Janab >= 300 )
                {
                        z = 0.6*kitna_unit_jaoge_Janab;
                }

            rupia_btauu = meret_charge + x + y + z ;
            printf("\n\n *******\tNAME: %s\t*******\n", name);
             printf("\t\t CHARGE: %.2f\t\n", rupia_btauu);

        }
    return 0;
}

>>SIR! @dbc2201 PLEASE CHECK IT.

**Comment by dbc2201** [comment]
@RakeshY008 you can use this link to write and share your code snippet with others https://gist.github.com/.
Go to [this](https://gist.github.com/dbc2201/7685e8df0d3eb8265af849c7513e62db) link for a sample solution of this problem.
