### ISSUE TITLE
worksheet 2 : doubt in Question 3,19

### ISSUE THREAD

**Issue by krishnaguptaa** [dbc2201/gla-bcsc0001-2018#42]
int main()
{
    printf("%f  %f  %f  %f", 6 / 5, -6 / 5, 6 / -5, -6 / -5);
    return 0;
}
            &

int main()
{
    int a = 10;
	int b = 30;
	float c;
	c = a % b++ + b / a--;
	printf("%f", c--);
    return 0;
}

**Comment by dbc2201** [comment]
Hey @8979184740 , could you please tell me your doubt regarding this code?
Also, *just a suggestion*, you could have had a better username than the current one. :disappointed:

**Comment by dbc2201** [comment]
You can view #20 for the explanation of Question 3 Worksheet 2
