### ISSUE TITLE
Doubt in worksheet 1

### ISSUE THREAD

**Issue by siddharth1806** [dbc2201/gla-bcsc0001-2018#46]
#include <stdio.h>
int a;
int b;
int c;
int main()
{
    if(a == b == b == c)
    {
        printf("%d %d %d", a, b, c);
    }
    return 0;
}

**Comment by dbc2201** [comment]
@siddharth1806 could you please explain what is your doubt regarding this code?

**Comment by anandmcts1** [comment]
In some compiler all global variable treated as initialized as '0' if no value assign to it.
Or some compiler shows error bcoz variable not get memories without initiate.

**Comment by dbc2201** [comment]
Hey @siddharth1806 , see #24 for this.
