### ISSUE TITLE
Doubt in worksheet 1 

### ISSUE THREAD

**Issue by sparshgupta2212** [dbc2201/gla-bcsc0001-2018#47]
#include <stdio.h>
int a = 10;
int b = 10;
int c = 10;
int main()
{
    if(a == b == b == c)
    {
        printf("%d %d %d", a, b, c);
    }
    return 0;
}

**Comment by dbc2201** [comment]
@sparshgupta2212 this is a duplicate question.

**Comment by dbc2201** [comment]
Hey @sparshgupta2212 , see #24 for this.
