### ISSUE TITLE
Doubt in worksheet _1 Q no 13

### ISSUE THREAD

**Issue by sparshgupta2212** [dbc2201/gla-bcsc0001-2018#49]
#include <stdio.h>
int a = 5;
int main()
{
    int a = 10;   
    if (printf("hello") == a)
        printf("student");
    return 0;
}

**Comment by dbc2201** [comment]
Hey, @sparshgupta2212 !
Could you tell us your doubt regarding the code?

**Comment by sparshgupta2212** [comment]
I have understand the solution of this question
