### ISSUE TITLE
thanks for creating repository  

### ISSUE THREAD

**Issue by g-rishabh** [dbc2201/gla-bcsc0001-2018#5]
Thanks, for creating this repository for us.This will surely improve everyone's coding skills.

**Comment by dbc2201** [comment]
Thank you for the positive review @g-rishabh. I always strive to create a better learning ecosystem for the students. I am happy that you feel that this initiative holds some potential to help the students. I believe you and other students as well will also join me in the cause. I am always open to new ideas, so if you have any, please share them with me or the class!
