### ISSUE TITLE
Work sheet 4 ques. 12

### ISSUE THREAD

**Issue by kartikvar1411** [dbc2201/gla-bcsc0001-2018#51]
#include <stdio.h>
int a = 10;
int b = 10;
int c = 10;
int main()
{
    if(a == b == b == c)
    {
	    printf("%d %d %d", a, b, c);
    }
    return 0;
}
why 'if' is not working?

**Comment by dbc2201** [comment]
Hey, @kartikvar1411  I believe #24 would be the solution to this.
