### ISSUE TITLE
Worksheet 3 ques 11

### ISSUE THREAD

**Issue by kartikvar1411** [dbc2201/gla-bcsc0001-2018#52]
ques.11
int main(void)
{
    int f = 65.235;
	printf("%d %d", f = f << 1, f = f << 2);
    return 0;
}
How it will evaluate this statement,
printf("%d %d", f = f << 1, f = f << 2);

**Comment by dbc2201** [comment]
Hey @kartikvar1411 , you can find a nice little guide to Bitwise Operators in C [here](https://dev.to/noah11012/bitwise-operations-in-cc-3j3k). I recommend a read! :fire: 
___
Nonetheless, the answer to your question is, we would have to perform bitwise operations. 
#24 would provide you with the explanation you need,

**Comment by kartikvar1411** [comment]
Ok sir...
