### ISSUE TITLE
please sir check the coad,worksheet no 6 questio no 5; and sugess me  doing this program another way

### ISSUE THREAD

**Issue by Kishanlalbind** [dbc2201/gla-bcsc0001-2018#54]
#include<stdio.h>
int main()
{
    int x;
    printf("inter the number");
    scanf("%d",&x);
    printf("%d, %d, %d, %d",x*x, x*x*x, x*x*x*x, x*x*x*x*x);
    return 0;
}

**Comment by shivamyadav37** [comment]
too much errors in the code , you are using undeclared variables in the code
and it's not mathematics , you have to use '*' for multiplication

**Comment by dbc2201** [comment]
Hey, @Kishanlalbind It's written `code` not `coad`, `suggest` not `sugess`.
@shivamyadav37 is right. You need to use `*` for multplying two values in C.
Hence the line `printf("%d, %d, %d, %d",xx, xxx, xxxx, xxxxx);` will change to
`printf("%d, %d, %d, %d", x*x, x*x*x, x*x*x*x, x*x*x*x*x);`
