### ISSUE TITLE
plz sir chech the the program worksheet no 6 question no 7

### ISSUE THREAD

**Issue by Kishanlalbind** [dbc2201/gla-bcsc0001-2018#55]
/*Write a program in C to read coordinates of two points and calculate the distance between them as per following formula:*/
#include<stdio.h>
int main()
{
    int x1,y1,x2,y2;
    float d;
    printf("enter the first qudrant:\n");
    scanf("%d %d",&x1,&y1);
    printf("enter the second qudrant\n");
    scanf("%d %d",&x2,&y2);
    d=pow((pow(x1-x2,2)+pow(y1-y2,2)),0.5);
    printf("%f",d);
    return 0;
}

**Comment by vijaytyagi369** [comment]
#include<stdio.h>
//Call maths library before using its functions.
#include<math.h>
int main()
{
int x1,y1,x2,y2;
float d;
printf("enter the first qudrant:\n");
scanf("%d %d",&x1,&y1);
printf("enter the second qudrant\n");
scanf("%d %d",&x2,&y2);
d=pow((pow(x1-x2,2)+pow(y1-y2,2)),0.5);
printf("%f",d);
return 0;
}

**Comment by dbc2201** [comment]
@Kishanlalbind, Try the code given below
```c
#include <stdio.h>
#include <math.h>
int main()
{
    double x1 = 0.0, y1 = 0.0, x2 = 0.0, y2 = 0.0;
    double d = 0.0;
    printf("enter the first point:\n");
    scanf("%lf %lf", &x1, &y1);
    printf("enter the second point\n");
    scanf("%lf %lf", &x2, &y2);
    double x = pow((x2 - x2), 2);
    double y = pow((y2 - y1), 2);
    d = pow((x + y), 0.5);
    printf("The distance is %.2lf units",d);
    return 0;
}
```

**Comment by dbc2201** [comment]
You had used the function `pow()` without including the header file `math.h`. 
This would give you an error. Also, instead of writing complex equations in a single statement, like this
`d=pow((pow(x1-x2,2)+pow(y1-y2,2)),0.5);`
It is better to break it up in multiple statements.
```C
double x = pow((x2 - x2), 2);
    double y = pow((y2 - y1), 2);
    d = pow((x + y), 0.5);
```
