### ISSUE TITLE
Doubt in Worksheet 2

### ISSUE THREAD

**Issue by sparshgupta2212** [dbc2201/gla-bcsc0001-2018#59]
int main()
{
    int i = 0;
	printf("%d" ,++i * ++i);
	return 0;
}

Sir I can't understand the output of this question..

**Comment by divaibhav** [comment]
in the below code line
**printf("%d"** ,++i * **++i);**

it is solving from right to to left so the last **"++i" is evaluated which make i=1**, and then compiler checked  for the completion of expression before using value of "i". As the expression is not completing compiler again solved **"++i" which makes i=2**, then the complete expression is solved as 2 * 2.

**note:**
this is in case of pre increment only, in post increment result is different for same value of i
