### ISSUE TITLE
my repo for worksheet1 and solutions

### ISSUE THREAD

**Issue by shivamyadav37** [dbc2201/gla-bcsc0001-2018#6]
https://github.com/shivamyadav37/C_Programming_Worksheet_1

**Comment by Mystery01092000** [comment]
?? whats the issue? mention it

**Comment by dbc2201** [comment]
@Mystery01092000, there's no issue. This was part of the worksheet assignment.

**Comment by shivamyadav37** [comment]
whole source and solutions uploaded!!

**Comment by dbc2201** [comment]
Good job!
