### ISSUE TITLE
C-quiz project(need help in it)

### ISSUE THREAD

**Issue by RakeshY008** [dbc2201/gla-bcsc0001-2018#64]
Link of Quiz-project: 

https://github.com/RakeshY008/Learning-in-fun/tree/master/Project-in-C/MCQ%20Quiz/Quiz/Quiz

:100: :computer: @dbc2201 :1st_place_medal:

**Comment by RakeshY008** [comment]
:1st_place_medal: @dbc2201 
 Sir new link of my  Quiz :1234: 
problem: not getting Player name and marks scored in quiz........

https://github.com/RakeshY008/Project-in-C/tree/master/Quiz

**Comment by RakeshY008** [comment]
sir new link of my project : 
i have corrected my previous mistake i.e,. comments where required.

https://github.com/RakeshY008/Project-in-C/blob/master/main.c

note: sir i want you to help me now in making same code using file-handling concept.

**Comment by dbc2201** [comment]
Link not working
