### ISSUE TITLE
doubt in code of worksheet question 4

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/gla-bcsc0001-2018#7]
https://gist.github.com/dbc2201/a4f80e7f8bbcdda92cfc419624cb9453
Here's the code, can anyone help?
```C
#include <stdio.h>
int main()
{
    int a = 1;
    if (a);
    {
        printf("hello");
    }
    else
    {
        printf("world");
    }
    return 0;
}

**Comment by nik-1207** [comment]
https://github.com/dbc2201/gla-bcsc0001-2018/issues/8
Go to this link for solution

**Comment by dbc2201** [comment]
@kartikvar1411 you are correct. I will provide an explanation for the cause of this error later in this comment.
@nik-1207 you have referenced a link to another issue, but the explanation for the error is not present even in that link.
___
Explanation :
After the `if()` statement, we have put a semicolon `;`, hence the body of the `if` statement has been terminated.
What this means is, the
```c
{
        printf("hello");
}
```
is now not the part of `if`'s body. Even if the test condition of the `if` statement is false, this piece of code will run individually.
The cause of the error lies here because the `else` portion can only follow the body of an `if`. 
i.e the `if-else` should always be in continuation.
Now the effective statement is
```c
if ( condition ) ;

{
        statemen1;
}

else
{
        statement2;
}
```
As you can see from the code above, the `else` is not following the body of an `if` statement, but rather a **block** of code. Hence, the error, `misplaced else`(Turbo C++ IDE) *which you shouldn't be using btw* or `expected expression before 'else'` in GCC compiler (*CodeBlocks / Terminal / CMD ).
